# Generated by Django 4.1.1 on 2022-09-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0002_project_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="client",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="project",
            name="heading",
            field=models.CharField(default="", max_length=200),
        ),
    ]
